### ISSUE TITLE
my_class.htmlが存在しない

### ISSUE THREAD

**Issue by Se1getsu** [gomazarashi/ou_syllabus#3]
extract_textbook.pyを実行しようとするとエラーが出て実行できませんでした。
`FileNotFoundError: [Errno 2] No such file or directory: 'my_class.html'`

**Comment by gomazarashi** [comment]
当初からの想定として、履修時間割表のデータをユーザーが自ら取得し、それをmy_class.htmlに保存することで情報の読み取りをする、という設計でしたが、それではあまりにもユーザーに負担がかかるため、Seleniumを用いて半自動的に情報を取得する設計に変更致します。

**Comment by gomazarashi** [comment]
最新版にて、教科書情報の検索に用いる講義番号を、ローカルのHTMLからファイルではなく学務情報システム上の履修時間割表から取得するように仕様を変更いたしました。
